
apiVersion: v1

kind: Service

metadata:

  labels:

    app: mongo

  name: mongo-nodeport-svc

spec:

  ports:

  – port: 27017

    protocol: TCP

    targetPort: 27018

    nodePort: 32000

  selector:

    app: mongo

  type: NodePort

status:

  loadBalancer:{}


